# cloudbuild.yaml
steps:
# Debug step to show directory structure
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'debug'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "Workspace contents:"
    ls -la /workspace
    echo "Terraform directory contents:"
    ls -la /workspace/terraform

# Setup Terraform
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'setup'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    apk add --update curl unzip
    curl -LO https://releases.hashicorp.com/terraform/1.4.7/terraform_1.4.7_linux_amd64.zip
    unzip terraform_1.4.7_linux_amd64.zip
    mv terraform /usr/local/bin/

# Get cluster credentials
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'get-credentials'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials autopilot-cluster-1-test \
    --region asia-south1 \
    --project vishakha-403211

# Terraform Plan
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'terraform-plan'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    # Install Terraform
    apk add --update curl unzip
    curl -LO https://releases.hashicorp.com/terraform/1.4.7/terraform_1.4.7_linux_amd64.zip
    unzip terraform_1.4.7_linux_amd64.zip
    mv terraform /usr/local/bin/
    
    # Navigate to terraform directory and show contents
    cd /workspace/terraform
    echo "Contents of terraform directory:"
    ls -la
    
    # Run Terraform commands
    terraform init
    terraform plan -var-file="/workspace/terraform/main.tfvars" -out=tfplan
  workingDir: /workspace/terraform

# Manual approval
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'approval'
  entrypoint: 'sleep'
  args: ['infinity']
  waitFor: ['terraform-plan']

# Terraform Apply
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'terraform-apply'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    # Install Terraform
    apk add --update curl unzip
    curl -LO https://releases.hashicorp.com/terraform/1.4.7/terraform_1.4.7_linux_amd64.zip
    unzip terraform_1.4.7_linux_amd64.zip
    mv terraform /usr/local/bin/
    
    cd /workspace/terraform
    terraform init
    terraform apply -auto-approve tfplan
  workingDir: /workspace/terraform

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '3600s'
