# cloudbuild.yaml
steps:
# Get cluster credentials
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - 'autopilot-cluster-1-test'
  - '--region'
  - 'asia-south1'
  - '--project'
  - 'vishakha-403211'
  id: 'get-credentials'

# Initialize Terraform
- name: 'hashicorp/terraform:1.0.0'
  args: ['init']
  dir: 'terraform'
  id: 'terraform-init'
  waitFor: ['get-credentials']

# Plan Terraform changes
- name: 'hashicorp/terraform:1.0.0'
  args:
    - 'plan'
    - '-var-file=main.tfvars'
    - '-out=tfplan'
  dir: 'terraform'
  id: 'terraform-plan'
  waitFor: ['terraform-init']

# Approval step
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'approval'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      echo "Terraform Plan completed. Please review the plan above."
      echo "Build will pause for 10 minutes for manual approval."
      echo "Click 'Cancel' to abort the build if the plan is not acceptable."
      sleep 600
  waitFor: ['terraform-plan']

# Apply Terraform changes
- name: 'hashicorp/terraform:1.0.0'
  args: ['apply', '-auto-approve', 'tfplan']
  dir: 'terraform'
  id: 'terraform-apply'
  waitFor: ['approval']

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'  # 20 minute timeout
