steps:
- name: 'hashicorp/terraform:1.0.0'
  args: ['init']
  dir: 'terraform'

- name: 'hashicorp/terraform:1.0.0'
  args:
    - 'plan'
    - '-var-file=environments/main.tfvars'
    - '-out=tfplan'
  dir: 'terraform'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'alpha'
    - 'builds'
    - 'workflows'
    - 'wait-approval'
    - '--id=${BUILD_ID}'
    - '--project=${PROJECT_ID}'

- name: 'hashicorp/terraform:1.0.0'
  args: ['apply', '-auto-approve', 'tfplan']
  dir: 'terraform'

options:
  logging: CLOUD_LOGGING_ONLY
