# cloudbuild.yaml
steps:
# Debug step
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'debug'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "Workspace contents:"
    ls -la /workspace
    echo "Terraform directory contents:"
    ls -la /workspace/terraform

# Get credentials and install auth plugin
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  id: 'auth-setup'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    apt-get update
    apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
    export USE_GKE_GCLOUD_AUTH_PLUGIN=True
    echo "Auth plugin installed version:"
    gke-gcloud-auth-plugin --version
    gcloud container clusters get-credentials autopilot-cluster-1-test \
    --region asia-south1 \
    --project vishakha-403211
    # Create kubeconfig file that other steps can use
    echo "$$KUBECONFIG" > /workspace/kubeconfig
  env:
    - 'KUBECONFIG=/workspace/kubeconfig'

# Terraform Init
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-init'
  args: ['init']
  dir: 'terraform'
  waitFor: ['auth-setup']

# Terraform Plan
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-plan'
  args:
    - 'plan'
    - '-var-file=main.tfvars'
    - '-out=tfplan'
  dir: 'terraform'
  waitFor: ['tf-init']
  env:
    - 'KUBECONFIG=/workspace/kubeconfig'

# Terraform Apply
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-apply'
  args:
    - 'apply'
    - '-auto-approve'
    - 'tfplan'
  dir: 'terraform'
  waitFor: ['tf-plan']
  env:
    - 'KUBECONFIG=/workspace/kubeconfig'

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'KUBE_CONTEXT=gke_vishakha-403211_asia-south1_autopilot-cluster-1-test'
    - 'TF_VAR_project_id=vishakha-403211'
    - 'TF_VAR_region=asia-south1'
    - 'USE_GKE_GCLOUD_AUTH_PLUGIN=True'

timeout: '1800s'
