# cloudbuild.yaml
steps:
# Setup and authentication
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'setup'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    apk add --update unzip curl
    curl -LO https://releases.hashicorp.com/terraform/1.4.7/terraform_1.4.7_linux_amd64.zip
    unzip terraform_1.4.7_linux_amd64.zip
    mv terraform /usr/local/bin/
    gcloud components install gke-gcloud-auth-plugin

# Get cluster credentials
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'get-credentials'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials autopilot-cluster-1-test \
    --region asia-south1 \
    --project vishakha-403211

# Terraform Plan
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'terraform-plan'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    cd terraform
    terraform init
    terraform plan -var-file="main.tfvars" -out=tfplan
  waitFor: ['get-credentials']

# Manual approval
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'approval'
  entrypoint: 'sleep'
  args: ['infinity']
  waitFor: ['terraform-plan']

# Terraform Apply
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'terraform-apply'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    cd terraform
    terraform init
    terraform apply -auto-approve tfplan
  waitFor: ['approval']

substitutions:
  _LOCK_ID: ''  # Provide lock ID when needed

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '3600s'  # 1 hour timeout
