# cloudbuild-apply.yaml
steps:
# Get cluster credentials
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'get-credentials'
  args:
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - '${_CLUSTER_NAME}'
  - '--region'
  - '${_REGION}'
  - '--project'
  - '${PROJECT_ID}'
# Terraform Init
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-init'
  args:
    - 'init'
    - '-backend-config=bucket=${_BUCKET_NAME}'
    - '-backend-config=prefix=terraform/state'
  dir: 'terraform'
  waitFor: ['get-credentials']
# Terraform Apply
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-apply'
  args:
    - 'apply'
    - '-input=false'
    - '-auto-approve'
    - '-var-file=${_TFVARS_FILE}'
  dir: 'terraform'
  waitFor: ['tf-init']
options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'TF_VAR_project_id=${PROJECT_ID}'
    - 'TF_VAR_region=${_REGION}'
    - 'TF_IN_AUTOMATION=true'
    - 'TF_INPUT=0'
timeout: '1800s'
