# cloudbuild.yaml
steps:
# Debug step
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'debug'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "Workspace contents:"
    ls -la /workspace
    echo "Terraform directory contents:"
    ls -la /workspace/terraform

# Terraform Init
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-init'
  args: ['init']
  dir: 'terraform'

# Terraform State Remove (to handle existing resource)
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-state-remove'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    terraform state rm kubernetes_deployment.flask_app || true
  dir: 'terraform'

# Terraform Plan
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-plan'
  args:
    - 'plan'
    - '-var-file=main.tfvars'
    - '-out=tfplan'
    - '-input=false'
  dir: 'terraform'

# Terraform Apply
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-apply'
  args:
    - 'apply'
    - '-input=false'
    - '-auto-approve'
    - 'tfplan'
  dir: 'terraform'

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'TF_VAR_project_id=vishakha-403211'
    - 'TF_VAR_region=asia-south1'
    - 'TF_IN_AUTOMATION=true'
    - 'TF_INPUT=0'

timeout: '1800s'
