# cloudbuild-plan.yaml
steps:
# Get cluster credentials
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'get-credentials'
  args:
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - 'autopilot-cluster-1-test'
  - '--region'
  - 'asia-south1'
  - '--project'
  - 'vishakha-403211'

# Terraform Init
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-init'
  args: ['init']
  dir: 'terraform'

# Import existing deployment into Terraform state
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-import'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    terraform init
    export TF_VAR_app_image=$(grep 'app_image' main.tfvars | cut -d'=' -f2- | tr -d ' "')
    terraform import kubernetes_deployment.flask_app default/flask-app || true
  dir: 'terraform'

# Terraform Plan
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-plan'
  args:
    - 'plan'
    - '-var-file=main.tfvars'
    - '-out=/workspace/terraform/tfplan'
    - '-input=false'
  dir: 'terraform'
  waitFor: ['tf-import']

# Trigger apply build
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'trigger-apply'
  args:
    - 'builds'
    - 'triggers'
    - 'run'
    - '5c2e6392-3307-4603-9107-95150b4a6092'  # Your apply trigger ID
    - '--branch=${BRANCH_NAME}'
    - '--project=vishakha-403211'
    - '--region=asia-south1'
  waitFor: ['save-plan']

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'TF_VAR_project_id=vishakha-403211'
    - 'TF_VAR_region=asia-south1'
    - 'TF_IN_AUTOMATION=true'
    - 'TF_INPUT=0'

substitutions:
  _BUCKET_NAME: 'vishakha-403211-tfstate'

timeout: '1800s'
