# cloudbuild.yaml
steps:
# Get GKE credentials
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - 'autopilot-cluster-1-test'
  - '--region'
  - 'asia-south1'
  - '--project'
  - 'vishakha-403211'
  id: 'get-credentials'

# Initialize Terraform
- name: 'hashicorp/terraform:1.0.0'
  args: ['init']
  dir: 'terraform'
  id: 'terraform-init'
  waitFor: ['get-credentials']

# Plan Terraform changes
- name: 'hashicorp/terraform:1.0.0'
  args:
    - 'plan'
    - '-var-file=main.tfvars'
    - '-out=tfplan'
  dir: 'terraform'
  id: 'terraform-plan'
  waitFor: ['terraform-init']

# Manual approval step
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Waiting for manual approval..."
      echo "Check Cloud Build logs and click 'Resume' to continue or 'Cancel' to abort."
      sleep infinity
  id: 'approval'
  waitFor: ['terraform-plan']

# Apply Terraform changes
- name: 'hashicorp/terraform:1.0.0'
  args: ['apply', '-auto-approve', 'tfplan']
  dir: 'terraform'
  id: 'terraform-apply'
  waitFor: ['approval']

options:
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY
