# cloudbuild-plan.yaml
steps:
# Get cluster credentials
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'get-credentials'
  args:
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - '${_CLUSTER_NAME}'
  - '--region'
  - '${_REGION}'
  - '--project'
  - '${PROJECT_ID}'
# Terraform Init
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-init'
  args: 
    - 'init'
    - '-backend-config=bucket=${_BUCKET_NAME}'
    - '-backend-config=prefix=terraform/state'
  dir: '${_TERRAFORM_DIR}'
  waitFor: ['get-credentials']
# Terraform Plan
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-plan'
  args:
    - 'plan'
    - '-var-file=${_TFVARS_FILE}'
    - '-out=/workspace/terraform/tfplan'
    - '-input=false'
  dir: '${_TERRAFORM_DIR}'
  waitFor: ['tf-init']
# Trigger apply build
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'trigger-apply'
  args:
    - 'builds'
    - 'triggers'
    - 'run'
    - '${_APPLY_TRIGGER_ID}'
    - '--branch=${BRANCH_NAME}'
    - '--project=${PROJECT_ID}'
    - '--region=${_REGION}'
  waitFor: ['tf-plan']
options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'TF_VAR_project_id=${PROJECT_ID}'
    - 'TF_VAR_region=${_REGION}'
    - 'TF_IN_AUTOMATION=true'
    - 'TF_INPUT=0'
timeout: '1800s'
