# cloudbuild.yaml
steps:
# Authenticate to GKE
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - 'autopilot-cluster-1-test'  # Replace with your actual GKE cluster name
  - '--region'
  - '${_REGION}'
  - '--project'
  - '${PROJECT_ID}'

# Initialize Terraform
- name: 'hashicorp/terraform:1.0.0'
  args: ['init']
  dir: 'terraform'

# Plan Terraform changes
- name: 'hashicorp/terraform:1.0.0'
  args:
    - 'plan'
    - '-var-file=environments/dev.tfvars'
    - '-out=tfplan'
  dir: 'terraform'

# Wait for approval
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'alpha'
    - 'builds'
    - 'workflows'
    - 'wait-approval'
    - '--id=${BUILD_ID}'
    - '--project=${PROJECT_ID}'

# Apply Terraform changes
- name: 'hashicorp/terraform:1.0.0'
  args: ['apply', '-auto-approve', 'tfplan']
  dir: 'terraform'

substitutions:
  _REGION: 'asia-south1'  # Your GKE cluster region


options:
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY
