# cloudbuild.yaml
steps:
# Setup environment
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'setup'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    # Update and install required packages
    apk update
    apk add --no-cache curl unzip python3 py3-pip

    # Install Google Cloud components
    pip3 install google-cloud-sdk google-auth-oauthlib

    # Install kubectl
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    mv kubectl /usr/local/bin/

    # Install gke-gcloud-auth-plugin
    gcloud components install gke-gcloud-auth-plugin --quiet

    # Install Terraform
    curl -LO https://releases.hashicorp.com/terraform/1.4.7/terraform_1.4.7_linux_amd64.zip
    unzip terraform_1.4.7_linux_amd64.zip
    mv terraform /usr/local/bin/
    
    # Verify installations
    terraform version
    kubectl version --client
    echo "Setup completed"

# Get cluster credentials
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'get-credentials'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    # Install kubectl again (new container)
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    mv kubectl /usr/local/bin/
    
    # Set auth plugin environment variable
    export USE_GKE_GCLOUD_AUTH_PLUGIN=True
    
    # Get cluster credentials
    gcloud container clusters get-credentials autopilot-cluster-1-test \
    --region asia-south1 \
    --project vishakha-403211
    
    # Verify cluster access
    kubectl version --client
    echo "Credentials configured"

# Terraform Plan
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'terraform-plan'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    # Install Terraform (new container)
    apk add --update curl unzip
    curl -LO https://releases.hashicorp.com/terraform/1.4.7/terraform_1.4.7_linux_amd64.zip
    unzip terraform_1.4.7_linux_amd64.zip
    mv terraform /usr/local/bin/
    
    # Run Terraform commands
    terraform init
    terraform plan -var-file="main.tfvars" -out=tfplan
  dir: 'terraform'
  waitFor: ['get-credentials']

# Manual approval
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'approval'
  entrypoint: 'sleep'
  args: ['infinity']
  waitFor: ['terraform-plan']

# Terraform Apply
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'terraform-apply'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    # Install Terraform (new container)
    apk add --update curl unzip
    curl -LO https://releases.hashicorp.com/terraform/1.4.7/terraform_1.4.7_linux_amd64.zip
    unzip terraform_1.4.7_linux_amd64.zip
    mv terraform /usr/local/bin/
    
    # Run Terraform apply
    terraform init
    terraform apply -auto-approve tfplan
  dir: 'terraform'
  waitFor: ['approval']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '3600s'
