# cloudbuild.yaml
steps:
# Setup environment
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'setup'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    # Update and install required packages
    apk update
    apk add --no-cache curl unzip
    
    # Install Terraform
    curl -LO https://releases.hashicorp.com/terraform/1.4.7/terraform_1.4.7_linux_amd64.zip
    unzip terraform_1.4.7_linux_amd64.zip
    mv terraform /usr/local/bin/
    
    # Show directory structure
    echo "Current directory structure:"
    ls -R

# Get cluster credentials
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'get-credentials'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials autopilot-cluster-1-test \
    --region asia-south1 \
    --project vishakha-403211

# Terraform Plan
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'terraform-plan'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    # Install Terraform
    apk add --update curl unzip
    curl -LO https://releases.hashicorp.com/terraform/1.4.7/terraform_1.4.7_linux_amd64.zip
    unzip terraform_1.4.7_linux_amd64.zip
    mv terraform /usr/local/bin/
    
    # Show current directory and contents
    pwd
    ls -la
    
    # Change to terraform directory and show contents
    cd terraform
    ls -la
    
    # Run Terraform commands
    terraform init
    terraform plan -var-file="main.tfvars" -out=tfplan
  waitFor: ['get-credentials']

# Manual approval
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'approval'
  entrypoint: 'sleep'
  args: ['infinity']
  waitFor: ['terraform-plan']

# Terraform Apply
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: 'terraform-apply'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    # Install Terraform
    apk add --update curl unzip
    curl -LO https://releases.hashicorp.com/terraform/1.4.7/terraform_1.4.7_linux_amd64.zip
    unzip terraform_1.4.7_linux_amd64.zip
    mv terraform /usr/local/bin/
    
    cd terraform
    terraform init
    terraform apply -auto-approve tfplan
  waitFor: ['approval']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '3600s'
