# cloudbuild.yaml
steps:
# Initialize Terraform
- name: 'hashicorp/terraform:1.0.0'
  args: ['init']
  dir: 'terraform'
  id: 'terraform-init'

# Plan Terraform changes
- name: 'hashicorp/terraform:1.0.0'
  args:
    - 'plan'
    - '-var-file=main.tfvars'
    - '-out=tfplan'
  dir: 'terraform'
  id: 'terraform-plan'
  waitFor: ['terraform-init']

# Manual approval step using sleep
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Waiting for manual approval..."
      echo "Check Cloud Build logs and click 'Resume' to continue or 'Cancel' to abort."
      sleep infinity
  id: 'approval'
  waitFor: ['terraform-plan']

# Apply Terraform changes
- name: 'hashicorp/terraform:1.0.0'
  args: ['apply', '-auto-approve', 'tfplan']
  dir: 'terraform'
  id: 'terraform-apply'
  waitFor: ['approval']

substitutions:
  _DEPLOYMENT_NAME: 'flask-app'
  _CONTAINER_NAME: 'flask-app'
  _NEW_IMAGE: 'asia-south1-docker.pkg.dev/vishakha-403211/test-tf/flask-app:latest'

options:
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY
