# cloudbuild.yaml
steps:
# Debug step
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'debug'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "Workspace contents:"
    ls -la /workspace
    echo "Terraform directory contents:"
    ls -la /workspace/terraform

# Terraform Init
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-init'
  args: ['init']
  dir: 'terraform'

# Import existing deployment
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-import'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    terraform init
    terraform import kubernetes_deployment.flask_app default/flask-app || true
  dir: 'terraform'

# Terraform Plan
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-plan'
  args:
    - 'plan'
    - '-var-file=main.tfvars'
    - '-out=tfplan'
  dir: 'terraform'
  waitFor: ['tf-import']

# Terraform Apply
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-apply'
  args:
    - 'apply'
    - '-auto-approve'
    - 'tfplan'
  dir: 'terraform'
  waitFor: ['tf-plan']

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'TF_VAR_project_id=vishakha-403211'
    - 'TF_VAR_region=asia-south1'

timeout: '1800s'
