# cloudbuild.yaml
steps:
# Debug step to show directory structure
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'debug'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "Workspace contents:"
    ls -la /workspace
    echo "Terraform directory contents:"
    ls -la /workspace/terraform

# Get cluster credentials
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'get-credentials'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials autopilot-cluster-1-test \
    --region asia-south1 \
    --project vishakha-403211

# Terraform Init
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-init'
  args: ['init']
  dir: 'terraform'
  waitFor: ['get-credentials']

# Terraform Plan
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-plan'
  args:
    - 'plan'
    - '-var-file=main.tfvars'
    - '-out=tfplan'
  dir: 'terraform'
  waitFor: ['tf-init']

# Manual approval
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'approve'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "Terraform plan completed. Please review the plan above."
    echo "Click 'Resume' to apply the changes or 'Cancel' to abort."
    sleep infinity

# Terraform Apply
- name: 'hashicorp/terraform:1.4.7'
  id: 'tf-apply'
  args:
    - 'apply'
    - '-auto-approve'
    - 'tfplan'
  dir: 'terraform'
  waitFor: ['approve']

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'KUBE_CONTEXT=gke_vishakha-403211_asia-south1_autopilot-cluster-1-test'
    - 'TF_VAR_project_id=vishakha-403211'
    - 'TF_VAR_region=asia-south1'

timeout: '1800s'
